// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InvalidParam InvalidParam
//
// swagger:model invalidParam
type InvalidParam struct {

	// param
	// Required: true
	Param *string `json:"param"`

	// reason
	Reason string `json:"reason,omitempty"`
}

// Validate validates this invalid param
func (m *InvalidParam) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParam(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InvalidParam) validateParam(formats strfmt.Registry) error {

	if err := validate.Required("param", "body", m.Param); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InvalidParam) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InvalidParam) UnmarshalBinary(b []byte) error {
	var res InvalidParam
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
